version: "2"
services:
  api:
    build: db
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d/:ro
  db:
    image: mysql:5.7
    container_name: "Flappy_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"



